name: ParksQuest
main: net.ryanhecht.ParksQuest.Main
version: 0.2
description: Parks and Quests, its in the name :)
author: RyanHecht_ & ItzPolar
commands:
  pq:
    description: Activates an armorstand
